import { chatList } from "@/app/lib/data"
import { ChatItem } from "@/app/ui/chatItem"
import { AngleBracket, NavbarIcon, GearIcon } from "@/app/ui/icons"
import Image from "next/image"
import { Google_Sans_Flex } from "next/font/google"

const googleSansFlex = Google_Sans_Flex({
    subsets: ['latin'],
    display: 'swap',
    weight: ['300', '400', '500', '700'], // Fallback weights generated by Next.js
    variable: '--font-sans',       // Expose it as a CSS Variable
});

export function Sidebar({ className }: { className?: string }) {
    return (
        <div className={`relative bg-white px-2.75 pt-4 border-solid border border-gray-200 dark:bg-[#1C1C1C] dark:border-none w-80 flex flex-col justify-left h-screen rounded-r-2xl transition-all duration-300 ease-out ${className}`}>

            <div className="relative z-10 w-full h-12 flex justify-between items-center pl-2.5 pr-4 shadow-[-10px_13px_6px_6px_rgb(255,255,255,0.99)] " >
                <div className="flex justify-center items-center gap-2.5">
                    <Image
                        src="https://www.gstatic.com/lamda/images/gemini_sparkle_aurora_33f86dc0c0257da337c63.svg"
                        width={28}
                        height={28}
                        alt="Gemini Logo"
                    />
                    <h1 className={`${googleSansFlex.className} font-normal dark:text-[#E0E0E0] text-[20px] text-black`}>Gemini</h1>
                </div>
                <NavbarIcon />
            </div>

            {/* Chat list section */}
            <div className="relative z-0 overflow-y-auto">
                <details className="group flex flex-col font-[455] text-[#757575]">
                    <summary className="list-none flex pl-3.75">Recent
                        <AngleBracket className="group-open:rotate-90 ml-2.25 w-3.25 h-3.2 fill-[#757575] mb-0.75" />
                    </summary>

                    <div className="group-not-open:hidden">
                        {chatList.map((item, index) => {
                            return (
                                <ChatItem key={index} text={item.title} />
                            )
                        })}
                    </div>
                </details>
            </div>

            {/* Settings and Avatar */}
            <div className="flex justify-between items-center h-24 pr-3 shadow-[-10px_-12px_10px_10px_rgb(255,255,255,0.99)]">
                <div className="flex items-center font-light gap-2">
                    <Image
                        width={30}
                        height={30}
                        src="/me2.png"
                        alt="Avatar Image"
                        className="rounded-full"
                    />
                    <div className="font-medium text-[16px] dark:text-[#E0E0E0] ">
                        Sanskar Bhusal
                    </div>
                </div>
                <GearIcon className="" />
            </div>
        </div>
    )
}