import { chatList } from "@/app/lib/data"
import { ChatItem } from "@/app/ui/chatItem"
import { AngleBracket, NavbarIcon } from "@/app/ui/icons"
import Image from "next/image"
import { Google_Sans_Flex } from "next/font/google"

const googleSansFlex = Google_Sans_Flex({
    subsets: ['latin'],
    display: 'swap',
    weight: ['300', '400', '500', '700'], // Fallback weights generated by Next.js
    variable: '--font-sans',       // Expose it as a CSS Variable
});

export function Sidebar({ className }: { className?: string }) {
    return (
        <div className={`bg-white px-2.75 pt-1.75 border-solid border border-gray-200 dark:bg-[#1E1F20] dark:border-none flex justify-left h-screen w-80 rounded-r-2xl transition-all duration-300 ease-out ${className}`}>
            <div className="w-full flex flex-col">

                <div className="w-full h-12 flex justify-between items-center pl-2.5 pr-4" >
                    <div className="flex justify-center items-center gap-2.5">
                        <Image
                            src="https://www.gstatic.com/lamda/images/gemini_sparkle_aurora_33f86dc0c0257da337c63.svg"
                            width={28}
                            height={28}
                            alt="Gemini Logo"
                        />
                        <h1 className={`${googleSansFlex.className} font-normal dark:text-[#E0E0E0] text-xl`}>Gemini</h1>
                    </div>
                    <NavbarIcon className="" />
                </div>

                {/* Chat list section */}
                <details className="group flex flex-col font-[455] text-[#757575]">
                    <summary className="list-none flex pl-3.75">
                        Recent
                        <AngleBracket className="group-open:rotate-90 ml-2.25 w-3.25 h-3.2 fill-[#757575] mb-0.75" />
                    </summary>

                    <div className="group-not-open:hidden">
                        {chatList.map((item, index) => {
                            return (
                                <ChatItem key={index} text={item.title} />
                            )
                        })}
                    </div>
                </details>

                {/* Settings and Avatar */}
                <div className="flex justify-between items-center h-13 pr-3">
                    <div className="flex items-center font-light gap-2">
                        <Image
                            width={30}
                            height={30}
                            src="/me2.png"
                            alt="Avatar Image"
                            className="rounded-full"
                        />
                        <div className="font-medium text-[16px] dark:text-[#E0E0E0] ">
                            Sanskar Bhusal
                        </div>
                    </div>
                    <svg
                        className="stroke-black stroke-[1.25px] dark:stroke-white"
                        width="30.75"
                        height="30.75"
                        viewBox="0 0 24 24"
                        fill="transparent"
                    >
                        <path d="M17.2994 10.4527L19.2267 10.7677C19.3846 10.7935 19.5003 10.9298 19.5 11.0896V12.883C19.5 13.0412 19.3865 13.1768 19.2303 13.2042L17.3004 13.543C17.1885 13.9298 17.0349 14.3022 16.8415 14.6543L17.9823 16.2382C18.0759 16.3679 18.0612 16.5463 17.9483 16.6595L16.6804 17.9283C16.5682 18.0401 16.3921 18.0561 16.2623 17.9645L14.6627 16.8424C14.3099 17.0387 13.9352 17.1952 13.5442 17.3103L13.2034 19.231C13.176 19.3865 13.0406 19.5 12.8825 19.5H11.0888C10.9294 19.5 10.7934 19.3849 10.7676 19.228L10.4493 17.3168C10.059 17.204 9.6823 17.0485 9.32585 16.8525L7.73767 17.9648C7.60821 18.0558 7.43178 18.0401 7.31992 17.9283L6.05198 16.6595C5.93947 16.5463 5.9248 16.3686 6.01741 16.2391L7.13958 14.6697C6.94163 14.3116 6.78444 13.9337 6.67062 13.5414L4.76905 13.2042C4.61349 13.1765 4.5 13.0412 4.5 12.883V11.0896C4.5 10.9304 4.61544 10.7941 4.77263 10.768L6.67421 10.4514C6.78868 10.0582 6.94586 9.68022 7.14316 9.32315L6.0347 7.73739C5.94371 7.60793 5.95937 7.43185 6.07122 7.32L7.33883 6.0525C7.452 5.94 7.62908 5.925 7.7592 6.01793L9.33433 7.14293C9.68817 6.94924 10.0639 6.795 10.4552 6.6825L10.767 4.77359C10.7927 4.61576 10.929 4.5 11.0888 4.5H12.8825C13.041 4.5 13.1763 4.61413 13.2037 4.77L13.5399 6.68935C13.929 6.8025 14.304 6.95837 14.6591 7.15467L16.2385 6.01957C16.3683 5.92598 16.5464 5.94065 16.6595 6.05348L17.9278 7.32098C18.0397 7.43315 18.0553 7.60957 17.9643 7.73902L16.8392 9.34239C17.0323 9.69424 17.1865 10.066 17.2994 10.4527ZM9.71725 12C9.71725 13.2607 10.7393 14.2826 12.0001 14.2826C13.2608 14.2826 14.2829 13.2607 14.2829 12C14.2829 10.7394 13.2608 9.71742 12.0001 9.71742C10.7393 9.71742 9.71725 10.7394 9.71725 12Z"></path>
                    </svg>
                </div>
            </div>
        </div >
    )
}